name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "db"
database_name = "newsnow"
database_id = "21b30bd0-772d-4584-849c-da787fcbd739"
